[colors]
[colors.primary]
background = "#17181a"
foreground = "#d4d4d4"

[colors.normal]
black   = "#17181a"
red     = "#b85d5d"
green   = "#7a9b7a"
yellow  = "#a89b6b"
blue    = "#6b8199"
magenta = "#997a8d"
cyan    = "#669999"
white   = "#d4d4d4"

[colors.bright]
black   = "#4a4a4a"
red     = "#c97676"
green   = "#8fb18f"
yellow  = "#bdb088"
blue    = "#7d96b0"
magenta = "#b08fa2"
cyan    = "#7db3b3"
white   = "#e8e8e8"

[colors.cursor]
text   = "#17181a"
cursor = "#d4d4d4"
