[colors]
[colors.primary]
background = "#17181a"
foreground = "#ede9df"

[colors.normal]
black   = "#17181a"
red     = "#c2a566"
green   = "#cab86d"
yellow  = "#bfaf78"
blue    = "#929dc3"
magenta = "#a7afbe"
cyan    = "#afb8c6"
white   = "#c9c1a7"

[colors.bright]
black   = "#888a8f"
red     = "#dfcda5"
green   = "#e5daae"
yellow  = "#ded5b4"
blue    = "#ccd2e5"
magenta = "#dbdfe5"
cyan    = "#e4e7ed"
white   = "#ede9df"

[colors.cursor]
text   = "#17181a"
cursor = "#ede9df"
